### ISSUE TITLE
Support for CORS and OPTIONS requests

### ISSUE THREAD

**Issue by fnahuelc** [robiwano/siesta#7]
I am attempting to create a basic REST API server using Siesta. However, I encountered an issue while trying to enable support for CORS on PUT requests. The browser initiates a preflight request in the form of an OPTIONS request, resulting in an "error 405 Method Not Allowed." Consequently, CORS verification fails.

I have inspected the code at [common.h](https://github.com/robiwano/siesta/blob/master/siesta/include/siesta/common.h#L15 ) couldn't find explicit support for OPTIONS requests. Is there a way to enable them?

If there is no direct support, are there any workarounds that could address this issue? 

Your assistance is greatly appreciated. Thanks in advance!

**Comment by robiwano** [comment]
Hi, yes, that is something I too have wanted to add support for, having used siesta for a small web-based control UI in an embedded system. There I had the possibility to make sure all requests go to the same domain though, so it was not a problem per se.

I'll have to read up on this for a while though :)

**Comment by robiwano** [comment]
Checking up on this, it seems it's as easy as adding the following header in your REST API handler function:

` resp.addHeader("access-control-allow-origin", "*");`

This allowed me to have the REST server on a different port than the HTTP server, otherwise I get "blocked by CORS policy" in Chrome.

Let me know how this works for you.

**Comment by robiwano** [comment]
Ok, got it to work in this PR: https://github.com/robiwano/siesta/pull/8

**Comment by robiwano** [comment]
Fixed in https://github.com/robiwano/siesta/commit/b43ab1eec674739aa772b864d74a9d7490cebd62

**Comment by fnahuelc** [comment]
Wow! That is awesome 👌! Thanks @robiwano
